String.toLocaleString({
    
	"it": {
		"%game-intro"           : "Join the <strong>Cupcakes!</strong>",
		"%restart-button"       : "Play Again",
		"%keep-playing-button"  : "Keep going",
		"%retry-button"         : "Try again",
		"%game-won"             : "You win!",
		"%game-over"            : "Game over!",
		"%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/starwars\">git.io/starwars</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-STARWARS #2048game",
		"%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
		'%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
		'%p0'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
	},
	
	"en": {
		"%game-intro"           : "Unisci le tessere e distruggi l&#x27;<strong>IMPERO!</strong>",
		"%restart-button"       : "Play Again",
		"%keep-playing-button"  : "Continua",
		"%retry-button"         : "Riprova",
		"%game-won"             : "Hai vinto!",
		"%game-over"            : "Hai perso!",
		"%game-explanation"     : "<strong class=\"important\">Come giocare:</strong> Usare i <strong>tasti freccia</strong> per muovere le tessere. Quando due tessere con lo stesso simbolo si scontrano c&#x27;&egrave; la <strong>promozione!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Nota:</strong> Questo sito <a href=\"http://git.io/starwars\">git.io/starwars</a> &egrave; uno spin-off della versione ufficiale di <a href=\"http://git.io/2048\">2048</a> creata da <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%tile-legend"          : "<strong class=\"important\">Legenda Tessere:</strong>",
		"%credits"              : "Icone Star Wars di <a href=\"http://sensibleworld.com/news/more-free-star-wars-icons/\" title=\"Free Star Wars Icons by Sensible World\">Jory Raphael</a>.",
		"%tweet1"               : "Ho raggiunto \"",
		"%tweet2"               : "\" a 2048-STARWARS #2048game",
		'%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
		'%p0'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
	}

});