String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Fashionistas!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/fashion\">git.io/fashion</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Fashion images by <a href=\"http://www.iconsflow.com/\" title=\"Icons Flow">Icons Flow</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-Fashion #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%1'                    : 'hanger',
    '%2'                    : 'sock',
    '%4'                    : 'bowtie',
    '%8'                    : 'hat',
    '%16'                   : 'beanie',
    '%32'                   : 'cap',
    '%64'                   : 'shoe',
    '%128'                  : 'pants',
    '%256'                  : 'blazer',
    '%512'                  : 'bikini',
    '%1024'                 : 'simple dress',
    '%2048'                 : 'strapless wrap dress',
    '%p1'                   : 'hanger',
    '%p2'                   : 'sock',
    '%p4'                   : 'bowtie',
    '%p8'                   : 'hat',
    '%p16'                  : 'beanie',
    '%p32'                  : 'cap',
    '%p64'                  : 'shoe',
    '%p128'                 : 'pants',
    '%p256'                 : 'blazer',
    '%p512'                 : 'bikini',
    '%p1024'                : 'simple dress',
    '%p2048'                : 'strapless wrap dress',		
  

	},

  "en": {
    "%game-intro"           : "Join the <strong>Fashionistas!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/fashion\">git.io/fashion</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Fashion images by <a href=\"http://www.iconsflow.com/\" title=\"Icons Flow">Icons Flow</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-Fashion #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%1'                    : 'hanger',
    '%2'                    : 'sock',
    '%4'                    : 'bowtie',
    '%8'                    : 'hat',
    '%16'                   : 'beanie',
    '%32'                   : 'cap',
    '%64'                   : 'shoe',
    '%128'                  : 'pants',
    '%256'                  : 'blazer',
    '%512'                  : 'bikini',
    '%1024'                 : 'simple dress',
    '%2048'                 : 'strapless wrap dress',
    '%p1'                   : 'hanger',
    '%p2'                   : 'sock',
    '%p4'                   : 'bowtie',
    '%p8'                   : 'hat',
    '%p16'                  : 'beanie',
    '%p32'                  : 'cap',
    '%p64'                  : 'shoe',
    '%p128'                 : 'pants',
    '%p256'                 : 'blazer',
    '%p512'                 : 'bikini',
    '%p1024'                : 'simple dress',
    '%p2048'                : 'strapless wrap dress',		
  

	},
